# @package _global_
lr_scheduler:
  scheduler:
    _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
    warmup_epochs: 5
    max_epochs: ${trainer.max_epochs}
    warmup_start_lr: 1e-4
    eta_min: 1e-10
  interval: epoch
